package vista;

import estructuras.Arte;
import estructuras.Persistencia;
import java.awt.Dimension;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import static vista.PanelPrincipal.jTelaPrincipal;

public class PaneldeBusqueda extends javax.swing.JInternalFrame {
     
    protected static void atualiza_Arte() {
        p.setupLer();

        if (p.getContinua() == true) {
            p.readRecords();
            p.cleanupLer();
            cad = p.getCad();
        }
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            for (Arte a : cad) {
                model.addRow(obj(a));
            }
        } catch (NullPointerException e) {

        }
    }
    static void atualizacao_Instantanea() {
        atualiza_Arte();
    }
    protected static Object[] obj(Arte a) {
        try {
            Object[] arte = {a.getTitulo(), a.getAño(), a.getNombre(), a.getCategoria(), a.getTombo()};
            return arte;
        } catch (Exception e) {
        }
        return null;
    }
    private void fecha_Janela() {
        this.dispose();
    }
    public void setPosicao() {
        Dimension d = jTelaPrincipal.getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    
    
    
    public PaneldeBusqueda() {
        initComponents();
        atualiza_Arte();
        getRootPane().setDefaultButton(jBPesquisaRes);
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSePesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoCategoria = new javax.swing.JRadioButton();
        cbCategoriaPesquisa = new javax.swing.JComboBox<>();
        botaoNomeArtista = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisaArtista = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jBPesquisaRes = new javax.swing.JButton();
        jBFecharPesquisa = new javax.swing.JButton();
        botaoTitulo = new javax.swing.JRadioButton();
        txtPesquisaNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "AÑO DE PRODUCCION", "ARTISTA", "CATEGORIA", "TOMBO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botaoCategoria.setText("Categoría");
        botaoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCategoriaActionPerformed(evt);
            }
        });

        cbCategoriaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Álbum", "Acuarela", "Collage", "Dibujo", "Escultura", "Fotografía", "Grabado", "Impresión", "Instalación", "Libro", "Múltiple", "Objeto", "WorkDesinc", "Realizar", "Pintura", "Alivio", "Tapiz", "Vídeo" }));
        cbCategoriaPesquisa.setToolTipText("Para buscar por categoría, seleccione la categoría del trabajo y marque la casilla Categoría.");
        cbCategoriaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaPesquisaActionPerformed(evt);
            }
        });

        botaoNomeArtista.setText("Nombre del Artista");
        botaoNomeArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNomeArtistaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Buscar Registro");

        jButton1.setText("Restaurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBPesquisaRes.setText("Buscar");
        jBPesquisaRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaResActionPerformed(evt);
            }
        });

        jBFecharPesquisa.setText("Registrar");
        jBFecharPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharPesquisaActionPerformed(evt);
            }
        });

        botaoTitulo.setText("Titulo de la Obra");
        botaoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSePesquisaLayout = new javax.swing.GroupLayout(jPanelSePesquisa);
        jPanelSePesquisa.setLayout(jPanelSePesquisaLayout);
        jPanelSePesquisaLayout.setHorizontalGroup(
            jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSePesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSePesquisaLayout.createSequentialGroup()
                        .addGroup(jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelSePesquisaLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(jButton1)
                                .addGap(48, 48, 48)
                                .addComponent(jBPesquisaRes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBFecharPesquisa))
                            .addGroup(jPanelSePesquisaLayout.createSequentialGroup()
                                .addComponent(botaoCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(cbCategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(botaoNomeArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtPesquisaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addComponent(botaoTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSePesquisaLayout.setVerticalGroup(
            jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSePesquisaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCategoria)
                    .addComponent(cbCategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNomeArtista)
                    .addComponent(txtPesquisaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTitulo)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSePesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBPesquisaRes)
                    .addComponent(jBFecharPesquisa))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText(" *Haga clic en el trabajo para ver los detalles y editar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaPesquisaActionPerformed

    private void botaoNomeArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNomeArtistaActionPerformed
        if (botaoNomeArtista.isSelected()) {
            txtPesquisaArtista.setEnabled(true);
            txtPesquisaNome.setEnabled(false);
            cbCategoriaPesquisa.setEnabled(false);
        }
        if (botaoNomeArtista.isSelected() == false) {
            txtPesquisaNome.setEnabled(true);
            cbCategoriaPesquisa.setEnabled(true);
        }
    }//GEN-LAST:event_botaoNomeArtistaActionPerformed

    private void botaoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCategoriaActionPerformed
        if (botaoCategoria.isSelected()) {
            cbCategoriaPesquisa.setEnabled(true);
            txtPesquisaArtista.setEnabled(false);
            txtPesquisaNome.setEnabled(false);
        }
        if (botaoCategoria.isSelected() == false) {
            txtPesquisaArtista.setEnabled(true);
            txtPesquisaNome.setEnabled(true);
        }
    }//GEN-LAST:event_botaoCategoriaActionPerformed

    private void botaoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTituloActionPerformed
        if (botaoTitulo.isSelected()) {
            txtPesquisaNome.setEnabled(true);
            txtPesquisaArtista.setEnabled(false);
            cbCategoriaPesquisa.setEnabled(false);
        }
        if (botaoTitulo.isSelected() == false) {
            txtPesquisaArtista.setEnabled(true);
            cbCategoriaPesquisa.setEnabled(true);
        }
    }//GEN-LAST:event_botaoTituloActionPerformed

    private void jBPesquisaResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaResActionPerformed
        if (botaoTitulo.isSelected()) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
            for (Arte a : cad) {
                if (txtPesquisaNome.getText().equals(a.getTitulo())) {
                    System.out.println(a.getTombo());
                    modelo.addRow(obj(a));
                }
            }
        }
        if (botaoNomeArtista.isSelected()) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
            for (Arte a : cad) {
                if (txtPesquisaArtista.getText().equals(a.getNombre())) {
                    System.out.println(a.getTombo());
                    modelo.addRow(obj(a));
                }
            }
        }
        if (botaoCategoria.isSelected()) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setNumRows(0);
            for (Arte a : cad) {
                if (a.getCategoria().equals(String.valueOf(cbCategoriaPesquisa.getSelectedItem()))) {
                    System.out.println(a.getTombo());
                    modelo.addRow(obj(a));
                }
            }
        }
    }//GEN-LAST:event_jBPesquisaResActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBFecharPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharPesquisaActionPerformed
        PaneldeRegistro painelC = new PaneldeRegistro();
        jTelaPrincipal.add(painelC);
        painelC.setTitle("Cadastrar Obra de Arte");
        painelC.setVisible(true);
        painelC.setPosicao();
        this.dispose();
    }//GEN-LAST:event_jBFecharPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoCategoria;
    private javax.swing.JRadioButton botaoNomeArtista;
    private javax.swing.JRadioButton botaoTitulo;
    private javax.swing.JComboBox<String> cbCategoriaPesquisa;
    private javax.swing.JButton jBFecharPesquisa;
    private javax.swing.JButton jBPesquisaRes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelSePesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPesquisaArtista;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables
 private static Persistencia p = new Persistencia();
    protected static LinkedList<Arte> cad = new LinkedList<Arte>();
}
